#!/usr/bin/env node
/**
 * openai-tailor.mjs — OpenAI-compatible CV Tailoring for career-ops
 *
 * Tailor your CV content with ANY OpenAI-compatible chat endpoint instead of Claude.
 * This is the headless companion to openai-eval.mjs. It takes an evaluation report
 * and the job description, applies anti-fabrication rules, and outputs a validated
 * structured draft for the deterministic renderer.
 *
 * Usage:
 *   node openai-tailor.mjs --jd ./jds/my-job.txt --report reports/001-company-2026.md
 *
 * Requires (for hosted endpoints):
 *   OPENAI_API_KEY (or --key)   — your provider key
 *   OPENAI_BASE_URL (or --url)  — the provider's OpenAI-compatible base
 *   OPENAI_MODEL (or --model)   — the model id
 */

import { readFileSync, existsSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname, basename } from 'path';
import { fileURLToPath } from 'url';
import { getCareerOpsRoot } from './path-resolver.mjs';
import * as yaml from 'js-yaml';
import { assertArtifactDraft } from './lib/artifact-draft.mjs';
import { resolveTemplate } from './cv-templates.mjs';
import { assertFacts } from './verify-cv-facts.mjs';

try {
  const { config } = await import('dotenv');
  config();
} catch { /* dotenv optional */ }

const ROOT = dirname(fileURLToPath(import.meta.url));
const DATA_ROOT = getCareerOpsRoot();

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------
const PATHS = {
  shared:   join(ROOT, 'modes', '_shared.md'),
  writing:  join(ROOT, 'modes', '_writing.md'),
  pdfMode:  join(ROOT, 'modes', 'pdf.md'),
  cv:       join(DATA_ROOT, 'cv.md'),
  profile:  join(DATA_ROOT, 'config', 'profile.yml'),
  output:   join(DATA_ROOT, 'output'),
};

// ---------------------------------------------------------------------------
// CLI argument parsing
// ---------------------------------------------------------------------------
const args = process.argv.slice(2);

if (args.length === 0 || args[0] === '--help' || args[0] === '-h') {
  console.log(`
╔══════════════════════════════════════════════════════════════════╗
║      career-ops — OpenAI-compatible CV Tailoring (Headless)      ║
╚══════════════════════════════════════════════════════════════════╝

  Tailor your CV content with any OpenAI-compatible API to output a validated draft.

  USAGE
    node openai-tailor.mjs --jd <path> --report <path>
    node openai-tailor.mjs --url <base> --model <id> --jd <path> --report <path>

  OPTIONS
    --jd <path>      Path to the Job Description text file
    --report <path>  Path to the evaluation report generated by openai-eval.mjs
    --model <id>     Model id            (env OPENAI_MODEL, default gpt-4o)
    --url <base>     OpenAI-compatible base URL, including any /v1
                     (env OPENAI_BASE_URL, default https://api.openai.com/v1)
    --key <key>      API key             (env OPENAI_API_KEY)
    --help           Show this help

  ENV
    OPENAI_API_KEY, OPENAI_BASE_URL, OPENAI_MODEL, OPENAI_TIMEOUT_MS

  EXAMPLES
    OPENAI_API_KEY=sk-... node openai-tailor.mjs --jd ./jds/job.txt --report reports/001-company-2026-01-01.md
`);
  process.exit(0);
}

// Parse flags
let jdPath     = '';
let reportPath = '';
let modelName  = process.env.OPENAI_MODEL || 'gpt-4o'; // Tailoring needs a smarter model default than eval
let baseUrl    = (process.env.OPENAI_BASE_URL || 'https://api.openai.com/v1').replace(/\/$/, '');
let apiKey     = process.env.OPENAI_API_KEY || '';

for (let i = 0; i < args.length; i++) {
  if (args[i] === '--jd' && args[i + 1]) {
    jdPath = args[++i];
  } else if (args[i] === '--report' && args[i + 1]) {
    reportPath = args[++i];
  } else if (args[i] === '--model' && args[i + 1]) {
    modelName = args[++i];
  } else if (args[i] === '--url' && args[i + 1]) {
    baseUrl = args[++i].replace(/\/$/, '');
  } else if (args[i] === '--key' && args[i + 1]) {
    apiKey = args[++i];
  }
}

if (!jdPath || !reportPath) {
  console.error('❌  Both --jd and --report are required. Run with --help for usage.');
  process.exit(1);
}

if (!existsSync(jdPath)) {
  console.error(`❌  JD file not found: ${jdPath}`);
  process.exit(1);
}
if (!existsSync(reportPath)) {
  console.error(`❌  Report file not found: ${reportPath}`);
  process.exit(1);
}

const jdText = readFileSync(jdPath, 'utf-8').trim();
const reportText = readFileSync(reportPath, 'utf-8').trim();

// Attempt to parse company slug and candidate name
const reportFilename = basename(reportPath);
const match = reportFilename.match(/^\d+-([a-z0-9-]+)-\d{4}-\d{2}-\d{2}\.md$/);
const companySlug = match ? match[1] : 'unknown-company';

// Extract role from report header (e.g., "# Evaluation: Company - Role Title")
let roleSlug = 'role';
const roleMatch = reportText.match(/^#\s+Evaluation:\s+[^-]+\s+-\s+(.+?)$/m);
if (roleMatch && roleMatch[1]) {
  roleSlug = roleMatch[1]
    .toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

// ---------------------------------------------------------------------------
// Endpoint + security guard.
// ---------------------------------------------------------------------------
let endpointHost;
{
  let parsed;
  try {
    parsed = new URL(baseUrl);
  } catch {
    console.error(`❌  Invalid OPENAI_BASE_URL: "${baseUrl}"`);
    process.exit(1);
  }
  endpointHost = parsed.hostname;
  const isLoopback = endpointHost === 'localhost' || endpointHost === '127.0.0.1' || endpointHost === '::1';

  if (!isLoopback && parsed.protocol !== 'https:') {
    console.error(`
❌  Refusing to use a non-HTTPS remote endpoint: ${baseUrl}
   Your data and API key would be sent in cleartext.
   Use an https:// endpoint, or http://localhost:... for a local server.
`);
    process.exit(1);
  }

  if (!isLoopback && !apiKey) {
    console.error(`
❌  No API key for ${endpointHost}.
   Set one and re-run: OPENAI_API_KEY=your_key node openai-tailor.mjs ...
`);
    process.exit(1);
  }
}

const endpoint = `${baseUrl}/chat/completions`;

// ---------------------------------------------------------------------------
// File helpers
// ---------------------------------------------------------------------------
function readFile(path, label, required = false) {
  if (!existsSync(path)) {
    if (required) {
      console.error(`❌  Required context file not found: ${label} at ${path}`);
      process.exit(1);
    }
    console.warn(`⚠️   ${label} not found at: ${path}`);
    return `[${label} not found — skipping]`;
  }
  return readFileSync(path, 'utf-8').trim();
}

// ---------------------------------------------------------------------------
// Load context files
// ---------------------------------------------------------------------------
console.log('\\n📂  Loading context files...');

const sharedContext  = readFile(PATHS.shared, 'modes/_shared.md', false);
// Writing guardrails (Voice DNA / Writing Style / Professional Writing) live in
// _writing.md since #1710 — a CV-tailoring script needs them, unlike the eval
// engines that read the eval-core _shared.md alone.
const writingContext = readFile(PATHS.writing, 'modes/_writing.md', false);
const pdfModeLogic   = readFile(PATHS.pdfMode, 'modes/pdf.md', false);
const cvContent      = readFile(PATHS.cv, 'cv.md', true);
const profileContent = readFile(PATHS.profile, 'config/profile.yml', true);
const profile = yaml.load(profileContent) || {};
const selectedTemplate = profile?.cv?.template || 'standard';
const configuredFormat = profile?.cv?.output_format || 'text';
if (!['text', 'html', 'pdf'].includes(configuredFormat)) {
  console.error(`❌  Unsupported cv.output_format: ${configuredFormat}`);
  process.exit(1);
}
resolveTemplate('cv', selectedTemplate, { format: configuredFormat === 'text' ? 'md' : 'html' });

// ---------------------------------------------------------------------------
// Build system prompt
// ---------------------------------------------------------------------------
const systemPrompt = `You are career-ops, an AI-powered CV tailoring engine.
You read a candidate's base CV, profile, an evaluation report, and a Job Description.
Your job is to apply strict anti-fabrication tailoring rules to return tailored CV content.

═══════════════════════════════════════════════════════
SYSTEM CONTEXT (_shared.md)
═══════════════════════════════════════════════════════
${sharedContext}

═══════════════════════════════════════════════════════
WRITING GUARDRAILS (_writing.md)
═══════════════════════════════════════════════════════
${writingContext}

═══════════════════════════════════════════════════════
PDF TAILORING MODE (pdf.md)
═══════════════════════════════════════════════════════
${pdfModeLogic}

CANDIDATE BASE CV & PROFILE
═══════════════════════════════════════════════════════
[cv.md]
${cvContent}

[config/profile.yml]
${profileContent}

═══════════════════════════════════════════════════════
IMPORTANT OPERATING RULES FOR THIS SESSION
═══════════════════════════════════════════════════════
1. NEVER invent skills, metrics, experience, outcomes, or decision authority the candidate does not have.
2. Inject keywords only by reformulating facts explicitly present in [cv.md] or [article-digest.md]. If a JD keyword cannot be mapped to source text, omit it.
3. Apply the 6-second clarity gate: strongest matching evidence first.
4. Return one JSON object containing only tailored CV content fields: candidate, summary, competencies, experience, projects, education, certifications, awards, interests, skills.
5. Do NOT return HTML, CSS, Markdown fences, layout, style, template, or page-break fields.
6. Return JSON only, with no conversational filler.`;

// ---------------------------------------------------------------------------
// Prompt caching (#1709, closing the gap in #2432) — same shape as
// openai-eval.mjs. This system prompt (shared + writing + pdf mode + HTML
// template + cv + profile, ~15K+ tokens) is byte-identical across every
// offer, yet was re-sent and re-billed each call.
//
// Host-gated on purpose: OpenAI-compatible gateways (OpenRouter, DeepSeek, …)
// honor an ephemeral `cache_control` breakpoint on the prefix and reuse it
// across back-to-back calls within the cache TTL. api.openai.com instead caches
// long prefixes automatically and may reject the non-standard field, so it gets
// a plain-string system message. Either way the prompt TEXT is unchanged.
export function buildSystemMessage(prompt, host) {
  if (host === 'api.openai.com') return { role: 'system', content: prompt };
  return {
    role: 'system',
    content: [{ type: 'text', text: prompt, cache_control: { type: 'ephemeral' } }],
  };
}

export function parseProviderContent(raw, { template, renderFormat, jobContext }) {
  const text = String(raw || '').trim();
  if (!text || /^```/.test(text) || /```$/.test(text)) {
    throw new Error('Provider response must be unfenced JSON content only');
  }
  let tailoredContent;
  try {
    tailoredContent = JSON.parse(text);
  } catch (err) {
    throw new Error(`Provider response is not valid JSON: ${err.message}`);
  }
  return assertArtifactDraft({
    artifact_type: 'cv',
    target_job_context: jobContext,
    candidate_facts: { sources: ['cv.md', 'config/profile.yml'] },
    tailored_content: tailoredContent,
    selected_template: template,
    render_format: renderFormat,
  });
}

// ---------------------------------------------------------------------------
// Call the OpenAI-compatible endpoint
// ---------------------------------------------------------------------------
const timeoutMs = parseInt(process.env.OPENAI_TIMEOUT_MS || '300000', 10);
if (Number.isNaN(timeoutMs) || timeoutMs <= 0) {
  console.error(`❌  Invalid OPENAI_TIMEOUT_MS: "${process.env.OPENAI_TIMEOUT_MS}" — must be a positive integer (milliseconds).`);
  process.exit(1);
}

console.log(`\n🔒  Privacy: your cv.md + JD will be sent to ${endpointHost}.`);
console.log(`🤖  Calling ${modelName} via ${endpointHost}... this may take a minute.\n`);

const headers = { 'Content-Type': 'application/json' };
if (apiKey) headers['Authorization'] = `Bearer ${apiKey}`;

let artifactDraft;
try {
  const res = await fetch(endpoint, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      model:    modelName,
      messages: [
        buildSystemMessage(systemPrompt, endpointHost),
        { role: 'user',   content: `EVALUATION REPORT:\n\n${reportText}\n\nJOB DESCRIPTION:\n\n${jdText}\n\nNow, return ONLY the tailored CV content object as JSON.` },
      ],
      stream:      false,
      temperature: 0.2,
    }),
    signal: AbortSignal.timeout(timeoutMs),
  });

  if (!res.ok) {
    const body = await res.text();
    console.error(`❌  API error: HTTP ${res.status}`);
    console.error(`    ${body.slice(0, 300)}`);
    process.exit(1);
  }

  const data = await res.json();
  const providerContent = data.choices?.[0]?.message?.content?.trim();
  if (!providerContent) {
    console.error('❌  The endpoint returned an empty response.');
    process.exit(1);
  }
  artifactDraft = parseProviderContent(providerContent, {
    template: selectedTemplate,
    renderFormat: configuredFormat,
    jobContext: { company: companySlug, role_title: roleSlug },
  });
} catch (err) {
  console.error(`❌  API call failed: ${err.message}`);
  process.exit(1);
}

try {
  assertFacts(JSON.stringify(artifactDraft.tailored_content), {
    label: 'provider CV draft',
    sourcePaths: [PATHS.cv, join(DATA_ROOT, 'article-digest.md')],
    configPath: join(DATA_ROOT, 'config', 'cv-facts.json'),
  });
} catch (err) {
  console.error(`❌  ${err.message}`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Save validated structured draft
// ---------------------------------------------------------------------------
try {
  if (!existsSync(PATHS.output)) {
    mkdirSync(PATHS.output, { recursive: true });
  }

  let candidateName = 'candidate';
  try {
    const profile = yaml.load(profileContent);
    if (profile && profile.name) {
      candidateName = profile.name;
    }
  } catch (err) {
    console.warn(`⚠️   Failed to parse profile.yml: ${err.message}`);
  }
  candidateName = candidateName
    .toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

  const filename = `cv-${candidateName}-${companySlug}.draft.json`;
  const draftPath = join(PATHS.output, filename);

  writeFileSync(draftPath, JSON.stringify(artifactDraft, null, 2) + '\n', 'utf-8');
  console.log(`\n✅  Structured CV draft saved: ${draftPath}`);

  const format = configuredFormat === 'text' ? ' --markdown' : '';
  const extension = configuredFormat === 'text' ? 'md' : 'html';
  console.log(`\n📄  Next step (render selected template):\n    node build-cv-html.mjs ${draftPath} ${join(PATHS.output, `cv-${candidateName}-${companySlug}.${extension}`)}${format}\n`);

} catch (err) {
  console.warn(`⚠️   Could not save HTML: ${err.message}`);
  process.exit(1);
}
